"""add user_category and notes to transactions

Revision ID: 012add76f6c2
Revises: bc48f5897070
Create Date: 2026-02-28 05:26:33.820912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012add76f6c2'
down_revision: Union[str, None] = 'bc48f5897070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_category', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'user_category')
    # ### end Alembic commands ###
