"""create consent_records table

Revision ID: 36d8fa5e12d7
Revises: 7740486cc35a
Create Date: 2026-03-04 22:25:51.939244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d8fa5e12d7'
down_revision: Union[str, None] = '7740486cc35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_records_consent_type', 'consent_records', ['consent_type'], unique=False)
    op.create_index('ix_consent_records_user_id', 'consent_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consent_records_user_id', table_name='consent_records')
    op.drop_index('ix_consent_records_consent_type', table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
