"""add_mfa_fields_to_users

Revision ID: a74b3828f467
Revises: 28098fbbb3e2
Create Date: 2026-03-03 22:49:03.073976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74b3828f467'
down_revision: Union[str, None] = '28098fbbb3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret_encrypted', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_codes_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled_at')
    op.drop_column('users', 'mfa_recovery_codes_encrypted')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret_encrypted')
    # ### end Alembic commands ###
