"""add balance_manual display_name is_hidden to accounts

Revision ID: c0530379f594
Revises: 012add76f6c2
Create Date: 2026-02-28 05:50:19.262387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0530379f594'
down_revision: Union[str, None] = '012add76f6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance_manual', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('balance_manual_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_hidden')
    op.drop_column('accounts', 'display_name')
    op.drop_column('accounts', 'balance_manual_updated_at')
    op.drop_column('accounts', 'balance_manual')
    # ### end Alembic commands ###
